### PR TITLE
1.17-fabric

### PR DESCRIPTION
**Pull request by quiqueck**
Converted fabric part to 1.17

### CODE REVIEW

**Comment by Paspartout** [comment]
Wow thanks! I was planing to do the same once forge releases their first 1.17 version but this looks great!
Since UDM uses architectury I think it doesn't really matter when to port it.
I will review this and pull it on the weekend probably.

**Comment by Paspartout** [comment]
Maybe it's a good idea to squash the commits though, not sure.
The version will probably 0.4 or 0.3.2 then for the port, even though there are no new features. Going back to 0.3.0 would be confusing imho.

**Comment by quiqueck** [comment]
We thank you :) We love this Mod, it is a must have :)

However, the CI appears to be failing. I got that error when I was building against architectury 3.0, so I am not sure what is happening there. I'll squash the commits and will test, if that error stille happens locally with an empty build environment...

**Comment by quiqueck** [comment]
Nope, that build error is still there when I use a fresh gradle. I'll try to figure out how to fix this...

**Comment by quiqueck** [comment]
e08b6fe should fix the build errors on a fresh gradle

**Pull request merged**
